# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bryans/iso8601_dates

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bryans/iso8601_dates

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryans/iso8601_dates/CMakeFiles /home/bryans/iso8601_dates//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryans/iso8601_dates/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iso8601_dates

# Build rule for target.
iso8601_dates: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iso8601_dates
.PHONY : iso8601_dates

# fast build rule for target.
iso8601_dates/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/build
.PHONY : iso8601_dates/fast

src/filter.o: src/filter.c.o
.PHONY : src/filter.o

# target to build an object file
src/filter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/filter.c.o
.PHONY : src/filter.c.o

src/filter.i: src/filter.c.i
.PHONY : src/filter.i

# target to preprocess a source file
src/filter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/filter.c.i
.PHONY : src/filter.c.i

src/filter.s: src/filter.c.s
.PHONY : src/filter.s

# target to generate assembly for a file
src/filter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/filter.c.s
.PHONY : src/filter.c.s

src/is8601.o: src/is8601.c.o
.PHONY : src/is8601.o

# target to build an object file
src/is8601.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/is8601.c.o
.PHONY : src/is8601.c.o

src/is8601.i: src/is8601.c.i
.PHONY : src/is8601.i

# target to preprocess a source file
src/is8601.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/is8601.c.i
.PHONY : src/is8601.c.i

src/is8601.s: src/is8601.c.s
.PHONY : src/is8601.s

# target to generate assembly for a file
src/is8601.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/is8601.c.s
.PHONY : src/is8601.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/main.c.s
.PHONY : src/main.c.s

src/reader.o: src/reader.c.o
.PHONY : src/reader.o

# target to build an object file
src/reader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/reader.c.o
.PHONY : src/reader.c.o

src/reader.i: src/reader.c.i
.PHONY : src/reader.i

# target to preprocess a source file
src/reader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/reader.c.i
.PHONY : src/reader.c.i

src/reader.s: src/reader.c.s
.PHONY : src/reader.s

# target to generate assembly for a file
src/reader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/reader.c.s
.PHONY : src/reader.c.s

src/validate.o: src/validate.c.o
.PHONY : src/validate.o

# target to build an object file
src/validate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/validate.c.o
.PHONY : src/validate.c.o

src/validate.i: src/validate.c.i
.PHONY : src/validate.i

# target to preprocess a source file
src/validate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/validate.c.i
.PHONY : src/validate.c.i

src/validate.s: src/validate.c.s
.PHONY : src/validate.s

# target to generate assembly for a file
src/validate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/validate.c.s
.PHONY : src/validate.c.s

src/writer.o: src/writer.c.o
.PHONY : src/writer.o

# target to build an object file
src/writer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/writer.c.o
.PHONY : src/writer.c.o

src/writer.i: src/writer.c.i
.PHONY : src/writer.i

# target to preprocess a source file
src/writer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/writer.c.i
.PHONY : src/writer.c.i

src/writer.s: src/writer.c.s
.PHONY : src/writer.s

# target to generate assembly for a file
src/writer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso8601_dates.dir/build.make CMakeFiles/iso8601_dates.dir/src/writer.c.s
.PHONY : src/writer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... iso8601_dates"
	@echo "... src/filter.o"
	@echo "... src/filter.i"
	@echo "... src/filter.s"
	@echo "... src/is8601.o"
	@echo "... src/is8601.i"
	@echo "... src/is8601.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/reader.o"
	@echo "... src/reader.i"
	@echo "... src/reader.s"
	@echo "... src/validate.o"
	@echo "... src/validate.i"
	@echo "... src/validate.s"
	@echo "... src/writer.o"
	@echo "... src/writer.i"
	@echo "... src/writer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

